# Site settings
# These are used to personalize your new site.
title: Noah C Huber # your name here
logo: "/images/Head.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree
  Bachelor of Arts Applied Computing: Cybersecurity Concentration (Class of 2026) <br />
  <a href="pdf/Resume.pdf">View My Resume </a> <br />
github_username:  NoahCHuber # update with your username
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
# repository: "csci-csu/csci-portfolio"
# Build setting
theme: jekyll-theme-minimal

